// @ts-check
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { encodeCSource, sanitizeIdent, summarizeRanges } from '../src/format/csource.js';
import { encodeU8g2, decodeU8g2 } from '../src/format/u8g2.js';
import { encodeVlw } from '../src/format/vlw.js';
import { encodeBff, decodeBff } from '../src/format/bff.js';
import { loadFont } from '../src/fonts/loader.js';
import { subset } from '../src/model/subset.js';

test('sanitizeIdent / summarizeRanges', () => {
  assert.equal(sanitizeIdent('My Font-16'), 'My_Font_16');
  assert.equal(sanitizeIdent('16px'), 'font_16px');
  assert.equal(summarizeRanges([0x20, 0x21, 0x22, 0xb0]), 'U+0020-U+0022, U+00B0');
});

test('encodeCSource(u8g2): 埋め込んだ配列が encodeU8g2 と一致し、デコードできる', async () => {
  const font = subset(await loadFont('lgfxJapanGothic_16'), 'こんにちは012 A');
  const src = encodeCSource(font, {
    format: 'u8g2',
    symbolName: 'MyGothic16',
    attribution: { typeface: 'IPAexGothic', license: 'IPA Font License Agreement v1.0' },
  });

  // ヘッダの体裁
  assert.match(src, /Generated by LGFX Font Tool JS/);
  assert.match(src, /License\s+: IPA Font License Agreement v1\.0/);
  assert.match(src, /static const lgfx::U8g2font MyGothic16\(MyGothic16_data\);/);
  assert.match(src, /display\.setFont\(&MyGothic16\)/);

  // 配列を取り出してバイト一致とデコードを確認
  const m = /static const uint8_t MyGothic16_data\[(\d+)\][^=]*= \{([\s\S]*?)\};/.exec(src);
  assert.ok(m);
  const bytes = Uint8Array.from(
    /** @type {RegExpExecArray} */ (m)[2].match(/0x[0-9a-f]{2}/g)?.map(Number) ?? [],
  );
  assert.equal(bytes.length, Number(/** @type {RegExpExecArray} */ (m)[1]));
  const direct = encodeU8g2(font);
  assert.deepEqual([...bytes], [...direct]);
  const decoded = decodeU8g2(bytes);
  assert.equal(decoded.glyphs.size, font.glyphs.size);
});

test('encodeCSource(gfx): 連続集合は Adafruit 互換、飛び飛びは EncodeRange 付き', async () => {
  const free = await loadFont('FreeSans9pt7b');
  const plain = encodeCSource(free, { format: 'gfx', symbolName: 'FreeSans9Re' });
  assert.match(plain, /static const GFXfont FreeSans9Re LGFXFT_PROGMEM = \{/);
  assert.match(plain, /Adafruit GFX compatible/);
  assert.ok(!plain.includes('EncodeRange'), 'plain font must not use EncodeRange');

  const kana = subset(await loadFont('lgfxJapanGothic_16'), 'あいうえおABC');
  const ranged = encodeCSource(kana, { format: 'gfx', symbolName: 'KanaAbc' });
  assert.match(ranged, /static const lgfx::v1::EncodeRange KanaAbcRanges\[\]/);
  assert.match(ranged, /static const lgfx::v1::GFXfont KanaAbc = \{/);
  assert.match(ranged, /LovyanGFX extension/);
});

test('encodeCSource(vlw/bff): バイナリを変更せず配列へ埋め込む', async () => {
  const font = subset(await loadFont('lgfxJapanGothic_16'), '日本語A9');
  const bytesOf = (/** @type {string} */ src, /** @type {string} */ ident) => {
    const re = new RegExp(`static const uint8_t ${ident}_data\\[(\\d+)\\][^=]*= \\{([\\s\\S]*?)\\};`);
    const m = re.exec(src);
    assert.ok(m);
    const bytes = Uint8Array.from(m[2].match(/0x[0-9a-f]{2}/g)?.map(Number) ?? []);
    assert.equal(bytes.length, Number(m[1]));
    return bytes;
  };

  const vlw = encodeCSource(font, { format: 'vlw', symbolName: 'SmoothJa' });
  assert.deepEqual([...bytesOf(vlw, 'SmoothJa')], [...encodeVlw(font)]);
  assert.match(vlw, /display\.loadFont\(SmoothJa_data\)/);

  const bff = encodeCSource(font, { format: 'bff', symbolName: 'CompactJa', bpp: 2 });
  const bffBytes = bytesOf(bff, 'CompactJa');
  assert.deepEqual([...bffBytes], [...encodeBff(font, { bpp: 2 })]);
  assert.equal(/** @type {any} */ (decodeBff(bffBytes).meta.format).bff.bpp, 2);
  assert.match(bff, /display\.loadFont\(CompactJa_data, lgfx::IFont::font_type_t::ft_lvgl\)/);
});

test('encodeCSource: 説明コメントは指定言語、未指定時は英語', async () => {
  const font = subset(await loadFont('lgfxJapanGothic_16'), 'A9');
  const cases = /** @type {const} */ ([
    [undefined, 'Usage'],
    ['ja', '使い方'],
    ['zh-Hans', '用法'],
    ['zh-Hant', '用法'],
  ]);
  for (const [language, marker] of cases) {
    const src = encodeCSource(font, {
      format: 'vlw',
      symbolName: 'Localized',
      ...(language ? { language } : {}),
    });
    assert.match(src, new RegExp(`// ${marker}:  display\\.loadFont`));
  }
});
