// @ts-check
/**
 * C/C++ ソース出力（仕様 §6.3、UC1）。スケッチに貼れる .h を生成する。
 *
 * - u8g2: バイト配列 + lgfx::U8g2font ラッパ（LGFXScreenBuilder fontgen の
 *   emit.js の形式を踏襲。LovyanGFX / M5GFX でそのまま setFont(&Name) できる）
 * - gfx : Adafruit GFX 流の Bitmaps / Glyphs / GFXfont。飛び飛びの文字集合は
 *   LovyanGFX 拡張の EncodeRange 付きで出す（この場合 LovyanGFX 専用）
 *
 * 生成物の先頭には帰属表示を必ず埋め込む（仕様 §6.3 / §8.4）。OFL や Apache は
 * 派生フォントデータに表示の同伴を要求しており、生成された配列は派生データである。
 */
import { encodeU8g2 } from './u8g2.js';
import { encodeGfx, unpackGfxContainer } from './gfxfont.js';
import { FormatError } from '../util/errors.js';

/** @typedef {import('../model/font.js').Font} Font */

/** @param {number} b */
const HEX = (b) => '0x' + b.toString(16).padStart(2, '0');

/**
 * ユーザー入力から C の識別子を作る（先頭が数字なら接頭辞を付ける）。
 * @param {string} name
 */
export function sanitizeIdent(name) {
  const s = String(name || '').replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(s) ? s : 'font_' + s;
}

/**
 * コードポイント列を "U+0020-U+007E, U+00B0" 形式に要約する。
 * @param {number[]} cps
 * @param {number} [limit]
 */
export function summarizeRanges(cps, limit = 24) {
  if (!cps.length) return '(none)';
  /** @type {string[]} */
  const parts = [];
  const fmt = (/** @type {number} */ v) => `U+${v.toString(16).toUpperCase().padStart(4, '0')}`;
  let start = cps[0];
  let prev = cps[0];
  const push = () => parts.push(start === prev ? fmt(start) : `${fmt(start)}-${fmt(prev)}`);
  for (const c of cps.slice(1)) {
    if (c === prev + 1) {
      prev = c;
      continue;
    }
    push();
    start = prev = c;
  }
  push();
  if (parts.length <= limit) return parts.join(', ');
  return parts.slice(0, limit).join(', ') + `, … (+${parts.length - limit} more ranges)`;
}

/**
 * @typedef {object} Attribution
 * @property {string} [typeface] - 元書体名
 * @property {string} [author]
 * @property {string} [license]  - ライセンス名（例 'SIL Open Font License 1.1'）
 * @property {string} [licenseUrl]
 * @property {string} [origin]   - 入手元
 */

/**
 * 帰属・来歴コメント本文（ダウンロード前に UI で見せられるよう分離）。
 * @param {Font} font
 * @param {{ident: string, format: string, bytes: number, attribution?: Attribution}} info
 */
export function licenseNotice(font, info) {
  const a = info.attribution ?? {};
  const cps = [...font.glyphs.keys()].sort((x, y) => x - y);
  const L = [];
  L.push(`${info.ident} — embedded bitmap font`);
  L.push('');
  L.push('Generated by LGFX Font Tool JS');
  L.push('https://github.com/tanakamasayuki/LGFXFontToolJs');
  L.push('');
  L.push(`Typeface : ${a.typeface || font.familyName || '(unknown)'}`);
  if (a.author) L.push(`Author   : ${a.author}`);
  if (a.license || font.meta.license) {
    L.push(`License  : ${a.license ?? font.meta.license}`);
    if (a.licenseUrl) L.push(`           ${a.licenseUrl}`);
  } else {
    L.push('License  : UNKNOWN — supplied as a local file.');
    L.push('           You are responsible for confirming that this typeface may be');
    L.push('           embedded and redistributed in compiled firmware.');
  }
  if (a.origin) L.push(`Obtained : ${a.origin}`);
  if (font.meta.copyright) L.push(`Copyright: ${font.meta.copyright}`);
  L.push('');
  L.push('This file contains glyphs rasterized from the typeface above and is a');
  L.push('derived work of it. Keep this notice with the file and with any binary');
  L.push('built from it.');
  L.push('');
  L.push(`Format   : ${info.format}`);
  L.push(`Line box : ${font.ascent + font.descent}px (ascent ${font.ascent}, descent ${font.descent})`);
  L.push(`Glyphs   : ${font.glyphs.size}`);
  L.push(`Data     : ${info.bytes} bytes`);
  L.push(`Coverage : ${summarizeRanges(cps)}`);
  return L.join('\n');
}

/** @param {Uint8Array} data @param {string} indent */
function hexTable(data, indent) {
  const PER_LINE = 16;
  let s = '';
  for (let i = 0; i < data.length; i += PER_LINE) {
    s +=
      indent +
      Array.from(data.slice(i, i + PER_LINE), HEX).join(', ') +
      (i + PER_LINE < data.length ? ',' : '') +
      '\n';
  }
  return s;
}

/** @param {string} notice */
const asComment = (notice) => '// ' + notice.split('\n').join('\n// ') + '\n';

const PROGMEM_GUARD = `#ifndef LGFXFT_PROGMEM
  #if defined(PROGMEM)
    #define LGFXFT_PROGMEM PROGMEM
  #else
    #define LGFXFT_PROGMEM
  #endif
#endif
`;

/**
 * u8g2 形式の .h を出力する。
 * @param {Font} font
 * @param {string} ident
 * @param {Attribution | undefined} attribution
 * @param {{dropInvalid?: boolean}} encodeOpts
 */
function emitU8g2Header(font, ident, attribution, encodeOpts) {
  const data = encodeU8g2(font, encodeOpts);
  const guard = `LGFXFT_FONT_${ident.toUpperCase()}_H`;
  let s = asComment(
    licenseNotice(font, { ident, format: 'u8g2 (1bpp) — lgfx::U8g2font', bytes: data.length, attribution }),
  );
  s += '\n';
  s += `#ifndef ${guard}\n#define ${guard}\n\n`;
  s += '#include <stdint.h>\n\n';
  s += '// LovyanGFX（または同じ型を再輸出する M5GFX / M5Unified）を先に include して\n';
  s += '// lgfx::U8g2font が見えている必要があります。\n';
  s += '#if !defined(LGFX_USE_V1) && !defined(__LOVYANGFX_HPP__) && !defined(_M5GFX_H_)\n';
  s += '  #include <LovyanGFX.hpp>\n';
  s += '#endif\n\n';
  s += PROGMEM_GUARD + '\n';
  s += `static const uint8_t ${ident}_data[${data.length}] LGFXFT_PROGMEM = {\n`;
  s += hexTable(data, '  ');
  s += '};\n\n';
  s += `// 使い方:  display.setFont(&${ident});\n`;
  s += `static const lgfx::U8g2font ${ident}(${ident}_data);\n\n`;
  s += `#endif // ${guard}\n`;
  return s;
}

/**
 * GFXfont 形式の .h を出力する。
 * 単一範囲なら素の Adafruit GFX 互換、飛び飛びなら LovyanGFX 拡張（EncodeRange）。
 * @param {Font} font
 * @param {string} ident
 * @param {Attribution | undefined} attribution
 * @param {{dropInvalid?: boolean}} encodeOpts
 */
function emitGfxHeader(font, ident, attribution, encodeOpts) {
  const gfx = unpackGfxContainer(encodeGfx(font, encodeOpts));
  const ranged = gfx.ranges.length > 0;
  const bytes = gfx.bitmap.length + gfx.glyphs.length * 7 + gfx.ranges.length * 6 + 5;
  const guard = `LGFXFT_FONT_${ident.toUpperCase()}_H`;

  let s = asComment(
    licenseNotice(font, {
      ident,
      format: ranged
        ? 'GFXfont + EncodeRange (LovyanGFX extension; not plain Adafruit GFX)'
        : 'GFXfont (Adafruit GFX compatible)',
      bytes,
      attribution,
    }),
  );
  s += '\n';
  s += `#ifndef ${guard}\n#define ${guard}\n\n`;
  s += '#include <stdint.h>\n\n';
  if (ranged) {
    s += '// EncodeRange は LovyanGFX の拡張です。LovyanGFX / M5GFX 系でのみ使えます。\n';
    s += '#if !defined(LGFX_USE_V1) && !defined(__LOVYANGFX_HPP__) && !defined(_M5GFX_H_)\n';
    s += '  #include <LovyanGFX.hpp>\n';
    s += '#endif\n\n';
  } else {
    s += '// Adafruit GFX 互換。Adafruit_GFX なら gfxfont.h、LovyanGFX ならそのまま使えます。\n\n';
  }
  s += PROGMEM_GUARD + '\n';

  s += `static const uint8_t ${ident}Bitmaps[] LGFXFT_PROGMEM = {\n`;
  s += hexTable(gfx.bitmap, '  ');
  s += '};\n\n';

  const typePrefix = ranged ? 'lgfx::v1::' : '';
  s += `static const ${typePrefix}GFXglyph ${ident}Glyphs[] LGFXFT_PROGMEM = {\n`;
  gfx.glyphs.forEach((g, i) => {
    s += `  { ${g.bitmapOffset}, ${g.width}, ${g.height}, ${g.xAdvance}, ${g.xOffset}, ${g.yOffset} }${
      i + 1 < gfx.glyphs.length ? ',' : ''
    }\n`;
  });
  s += '};\n\n';

  if (ranged) {
    s += `static const lgfx::v1::EncodeRange ${ident}Ranges[] LGFXFT_PROGMEM = {\n`;
    gfx.ranges.forEach((r, i) => {
      s += `  { 0x${r.start.toString(16)}, 0x${r.end.toString(16)}, 0x${r.base.toString(16)} }${
        i + 1 < gfx.ranges.length ? ',' : ''
      }\n`;
    });
    s += '};\n\n';
    s += `// 使い方:  display.setFont(&${ident});\n`;
    s += `static const lgfx::v1::GFXfont ${ident} = {\n`;
    s += `  (uint8_t*)${ident}Bitmaps,\n`;
    s += `  (lgfx::v1::GFXglyph*)${ident}Glyphs,\n`;
    s += `  0x${gfx.first.toString(16)}, 0x${gfx.last.toString(16)}, ${gfx.yAdvance},\n`;
    s += `  ${gfx.ranges.length}, (lgfx::v1::EncodeRange*)${ident}Ranges };\n\n`;
  } else {
    s += `// 使い方:  display.setFont(&${ident});\n`;
    s += `static const GFXfont ${ident} LGFXFT_PROGMEM = {\n`;
    s += `  (uint8_t*)${ident}Bitmaps,\n`;
    s += `  (GFXglyph*)${ident}Glyphs,\n`;
    s += `  0x${gfx.first.toString(16)}, 0x${gfx.last.toString(16)}, ${gfx.yAdvance} };\n\n`;
  }
  s += `#endif // ${guard}\n`;
  return s;
}

/**
 * スケッチに貼れる C/C++ ソースを出力する（仕様 §6.3）。
 * @param {Font} font
 * @param {object} opts
 * @param {'u8g2' | 'gfx'} opts.format
 * @param {string} opts.symbolName - フォントオブジェクトの C 識別子
 * @param {Attribution} [opts.attribution]
 * @param {boolean} [opts.dropInvalid] - 制約違反グリフを落として続行（既定 false = エラー）
 * @returns {string}
 */
export function encodeCSource(font, opts) {
  const ident = sanitizeIdent(opts.symbolName);
  const encodeOpts = { dropInvalid: opts.dropInvalid };
  switch (opts.format) {
    case 'u8g2':
      return emitU8g2Header(font, ident, opts.attribution, encodeOpts);
    case 'gfx':
      return emitGfxHeader(font, ident, opts.attribution, encodeOpts);
    default:
      throw new FormatError('UNKNOWN_FORMAT', `no C source emitter for ${opts.format}`, {
        format: opts.format,
      });
  }
}
