// @ts-check
/**
 * C/C++ ソース出力（仕様 §6.3、UC1）。スケッチに貼れる .h を生成する。
 *
 * - u8g2: バイト配列 + lgfx::U8g2font ラッパ（LGFXScreenBuilder fontgen の
 *   emit.js の形式を踏襲。LovyanGFX / M5GFX でそのまま setFont(&Name) できる）
 * - gfx : Adafruit GFX 流の Bitmaps / Glyphs / GFXfont。飛び飛びの文字集合は
 *   LovyanGFX 拡張の EncodeRange 付きで出す（この場合 LovyanGFX 専用）
 *
 * 生成物の先頭には帰属表示を必ず埋め込む（仕様 §6.3 / §8.4）。OFL や Apache は
 * 派生フォントデータに表示の同伴を要求しており、生成された配列は派生データである。
 */
import { encodeU8g2, decodeU8g2 } from './u8g2.js';
import { encodeGfx, decodeGfx, unpackGfxContainer, packGfxContainer } from './gfxfont.js';
import { FormatError } from '../util/errors.js';

/** @typedef {import('../model/font.js').Font} Font */
/** @typedef {import('./gfxfont.js').GfxGlyphRec} GfxGlyphRec */

/** @param {number} b */
const HEX = (b) => '0x' + b.toString(16).padStart(2, '0');

/**
 * ユーザー入力から C の識別子を作る（先頭が数字なら接頭辞を付ける）。
 * @param {string} name
 */
export function sanitizeIdent(name) {
  const s = String(name || '').replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(s) ? s : 'font_' + s;
}

/**
 * コードポイント列を "U+0020-U+007E, U+00B0" 形式に要約する。
 * @param {number[]} cps
 * @param {number} [limit]
 */
export function summarizeRanges(cps, limit = 24) {
  if (!cps.length) return '(none)';
  /** @type {string[]} */
  const parts = [];
  const fmt = (/** @type {number} */ v) => `U+${v.toString(16).toUpperCase().padStart(4, '0')}`;
  let start = cps[0];
  let prev = cps[0];
  const push = () => parts.push(start === prev ? fmt(start) : `${fmt(start)}-${fmt(prev)}`);
  for (const c of cps.slice(1)) {
    if (c === prev + 1) {
      prev = c;
      continue;
    }
    push();
    start = prev = c;
  }
  push();
  if (parts.length <= limit) return parts.join(', ');
  return parts.slice(0, limit).join(', ') + `, … (+${parts.length - limit} more ranges)`;
}

/**
 * @typedef {object} Attribution
 * @property {string} [typeface] - 元書体名
 * @property {string} [author]
 * @property {string} [license]  - ライセンス名（例 'SIL Open Font License 1.1'）
 * @property {string} [licenseUrl]
 * @property {string} [origin]   - 入手元
 */

/**
 * 帰属・来歴コメント本文（ダウンロード前に UI で見せられるよう分離）。
 * @param {Font} font
 * @param {{ident: string, format: string, bytes: number, attribution?: Attribution}} info
 */
export function licenseNotice(font, info) {
  const a = info.attribution ?? {};
  const cps = [...font.glyphs.keys()].sort((x, y) => x - y);
  const L = [];
  L.push(`${info.ident} — embedded bitmap font`);
  L.push('');
  L.push('Generated by LGFX Font Tool JS');
  L.push('https://github.com/tanakamasayuki/LGFXFontToolJs');
  L.push('');
  L.push(`Typeface : ${a.typeface || font.familyName || '(unknown)'}`);
  if (a.author) L.push(`Author   : ${a.author}`);
  if (a.license || font.meta.license) {
    L.push(`License  : ${a.license ?? font.meta.license}`);
    if (a.licenseUrl) L.push(`           ${a.licenseUrl}`);
  } else {
    L.push('License  : UNKNOWN — supplied as a local file.');
    L.push('           You are responsible for confirming that this typeface may be');
    L.push('           embedded and redistributed in compiled firmware.');
  }
  if (a.origin) L.push(`Obtained : ${a.origin}`);
  if (font.meta.copyright) L.push(`Copyright: ${font.meta.copyright}`);
  L.push('');
  L.push('This file contains glyphs rasterized from the typeface above and is a');
  L.push('derived work of it. Keep this notice with the file and with any binary');
  L.push('built from it.');
  L.push('');
  L.push(`Format   : ${info.format}`);
  L.push(`Line box : ${font.ascent + font.descent}px (ascent ${font.ascent}, descent ${font.descent})`);
  L.push(`Glyphs   : ${font.glyphs.size}`);
  L.push(`Data     : ${info.bytes} bytes`);
  L.push(`Coverage : ${summarizeRanges(cps)}`);
  return L.join('\n');
}

/** @param {Uint8Array} data @param {string} indent */
function hexTable(data, indent) {
  const PER_LINE = 16;
  let s = '';
  for (let i = 0; i < data.length; i += PER_LINE) {
    s +=
      indent +
      Array.from(data.slice(i, i + PER_LINE), HEX).join(', ') +
      (i + PER_LINE < data.length ? ',' : '') +
      '\n';
  }
  return s;
}

/** @param {string} notice */
const asComment = (notice) => '// ' + notice.split('\n').join('\n// ') + '\n';

const PROGMEM_GUARD = `#ifndef LGFXFT_PROGMEM
  #if defined(PROGMEM)
    #define LGFXFT_PROGMEM PROGMEM
  #else
    #define LGFXFT_PROGMEM
  #endif
#endif
`;

/**
 * u8g2 形式の .h を出力する。
 * @param {Font} font
 * @param {string} ident
 * @param {Attribution | undefined} attribution
 * @param {{dropInvalid?: boolean}} encodeOpts
 */
function emitU8g2Header(font, ident, attribution, encodeOpts) {
  const data = encodeU8g2(font, encodeOpts);
  const guard = `LGFXFT_FONT_${ident.toUpperCase()}_H`;
  let s = asComment(
    licenseNotice(font, { ident, format: 'u8g2 (1bpp) — lgfx::U8g2font', bytes: data.length, attribution }),
  );
  s += '\n';
  s += `#ifndef ${guard}\n#define ${guard}\n\n`;
  s += '#include <stdint.h>\n\n';
  s += '// LovyanGFX（または同じ型を再輸出する M5GFX / M5Unified）を先に include して\n';
  s += '// lgfx::U8g2font が見えている必要があります。\n';
  s += '#if !defined(LGFX_USE_V1) && !defined(__LOVYANGFX_HPP__) && !defined(_M5GFX_H_)\n';
  s += '  #include <LovyanGFX.hpp>\n';
  s += '#endif\n\n';
  s += PROGMEM_GUARD + '\n';
  s += `static const uint8_t ${ident}_data[${data.length}] LGFXFT_PROGMEM = {\n`;
  s += hexTable(data, '  ');
  s += '};\n\n';
  s += `// 使い方:  display.setFont(&${ident});\n`;
  s += `static const lgfx::U8g2font ${ident}(${ident}_data);\n\n`;
  s += `#endif // ${guard}\n`;
  return s;
}

/**
 * GFXfont 形式の .h を出力する。
 * 単一範囲なら素の Adafruit GFX 互換、飛び飛びなら LovyanGFX 拡張（EncodeRange）。
 * @param {Font} font
 * @param {string} ident
 * @param {Attribution | undefined} attribution
 * @param {{dropInvalid?: boolean}} encodeOpts
 */
function emitGfxHeader(font, ident, attribution, encodeOpts) {
  const gfx = unpackGfxContainer(encodeGfx(font, encodeOpts));
  const ranged = gfx.ranges.length > 0;
  const bytes = gfx.bitmap.length + gfx.glyphs.length * 7 + gfx.ranges.length * 6 + 5;
  const guard = `LGFXFT_FONT_${ident.toUpperCase()}_H`;

  let s = asComment(
    licenseNotice(font, {
      ident,
      format: ranged
        ? 'GFXfont + EncodeRange (LovyanGFX extension; not plain Adafruit GFX)'
        : 'GFXfont (Adafruit GFX compatible)',
      bytes,
      attribution,
    }),
  );
  s += '\n';
  s += `#ifndef ${guard}\n#define ${guard}\n\n`;
  s += '#include <stdint.h>\n\n';
  if (ranged) {
    s += '// EncodeRange は LovyanGFX の拡張です。LovyanGFX / M5GFX 系でのみ使えます。\n';
    s += '#if !defined(LGFX_USE_V1) && !defined(__LOVYANGFX_HPP__) && !defined(_M5GFX_H_)\n';
    s += '  #include <LovyanGFX.hpp>\n';
    s += '#endif\n\n';
  } else {
    s += '// Adafruit GFX 互換。Adafruit_GFX なら gfxfont.h、LovyanGFX ならそのまま使えます。\n\n';
  }
  s += PROGMEM_GUARD + '\n';

  s += `static const uint8_t ${ident}Bitmaps[] LGFXFT_PROGMEM = {\n`;
  s += hexTable(gfx.bitmap, '  ');
  s += '};\n\n';

  const typePrefix = ranged ? 'lgfx::v1::' : '';
  s += `static const ${typePrefix}GFXglyph ${ident}Glyphs[] LGFXFT_PROGMEM = {\n`;
  gfx.glyphs.forEach((g, i) => {
    s += `  { ${g.bitmapOffset}, ${g.width}, ${g.height}, ${g.xAdvance}, ${g.xOffset}, ${g.yOffset} }${
      i + 1 < gfx.glyphs.length ? ',' : ''
    }\n`;
  });
  s += '};\n\n';

  if (ranged) {
    s += `static const lgfx::v1::EncodeRange ${ident}Ranges[] LGFXFT_PROGMEM = {\n`;
    gfx.ranges.forEach((r, i) => {
      s += `  { 0x${r.start.toString(16)}, 0x${r.end.toString(16)}, 0x${r.base.toString(16)} }${
        i + 1 < gfx.ranges.length ? ',' : ''
      }\n`;
    });
    s += '};\n\n';
    s += `// 使い方:  display.setFont(&${ident});\n`;
    s += `static const lgfx::v1::GFXfont ${ident} = {\n`;
    s += `  (uint8_t*)${ident}Bitmaps,\n`;
    s += `  (lgfx::v1::GFXglyph*)${ident}Glyphs,\n`;
    s += `  0x${gfx.first.toString(16)}, 0x${gfx.last.toString(16)}, ${gfx.yAdvance},\n`;
    s += `  ${gfx.ranges.length}, (lgfx::v1::EncodeRange*)${ident}Ranges };\n\n`;
  } else {
    s += `// 使い方:  display.setFont(&${ident});\n`;
    s += `static const GFXfont ${ident} LGFXFT_PROGMEM = {\n`;
    s += `  (uint8_t*)${ident}Bitmaps,\n`;
    s += `  (GFXglyph*)${ident}Glyphs,\n`;
    s += `  0x${gfx.first.toString(16)}, 0x${gfx.last.toString(16)}, ${gfx.yAdvance} };\n\n`;
  }
  s += `#endif // ${guard}\n`;
  return s;
}

/**
 * スケッチに貼れる C/C++ ソースを出力する（仕様 §6.3）。
 * @param {Font} font
 * @param {object} opts
 * @param {'u8g2' | 'gfx'} opts.format
 * @param {string} opts.symbolName - フォントオブジェクトの C 識別子
 * @param {Attribution} [opts.attribution]
 * @param {boolean} [opts.dropInvalid] - 制約違反グリフを落として続行（既定 false = エラー）
 * @returns {string}
 */
export function encodeCSource(font, opts) {
  const ident = sanitizeIdent(opts.symbolName);
  const encodeOpts = { dropInvalid: opts.dropInvalid };
  switch (opts.format) {
    case 'u8g2':
      return emitU8g2Header(font, ident, opts.attribution, encodeOpts);
    case 'gfx':
      return emitGfxHeader(font, ident, opts.attribution, encodeOpts);
    default:
      throw new FormatError('UNKNOWN_FORMAT', `no C source emitter for ${opts.format}`, {
        format: opts.format,
      });
  }
}

//----------------------------------------------------------------------------
// C/C++ ソースの読み込み（仕様 §6.3、UC5）。
// GitHub や Arduino ライブラリで配布される .h / .c を貼り付けたら読める、を
// 実現する。C プリプロセッサの完全実装はしない（実在のフォント配布ファイルが
// 読めれば足りる）。

/** @param {string} text */
function stripComments(text) {
  return text.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/\/\/[^\n]*/g, ' ');
}

/**
 * `{ ... }` の中の数値リストをバイト列にする。
 * @param {string} body
 */
function parseByteList(body) {
  const bytes = [];
  const re = /0[xX][0-9a-fA-F]+|\d+/g;
  let m;
  while ((m = re.exec(body)) !== null) bytes.push(Number(m[0]) & 0xff);
  return Uint8Array.from(bytes);
}

/**
 * C 文字列リテラル（連結可・8進/16進エスケープ対応）をバイト列にする。
 * u8g2 の bdfconv が出力する形式。
 * @param {string} text
 * @param {number} start - `=` の直後
 * @returns {Uint8Array}
 */
function parseCStringLiterals(text, start) {
  const bytes = [];
  let i = start;
  const n = text.length;
  let inString = false;
  while (i < n) {
    const ch = text[i];
    if (!inString) {
      if (ch === '"') {
        inString = true;
        i++;
      } else if (ch === ';') {
        break;
      } else {
        i++;
      }
      continue;
    }
    if (ch === '"') {
      inString = false;
      i++;
      continue;
    }
    if (ch === '\\') {
      i++;
      const e = text[i];
      if (e >= '0' && e <= '7') {
        let oct = '';
        while (oct.length < 3 && text[i] >= '0' && text[i] <= '7') oct += text[i++];
        bytes.push(parseInt(oct, 8) & 0xff);
      } else if (e === 'x') {
        i++;
        let hex = '';
        while (/[0-9a-fA-F]/.test(text[i])) hex += text[i++];
        bytes.push(parseInt(hex, 16) & 0xff);
      } else {
        i++;
        const map = { n: 10, t: 9, r: 13, a: 7, b: 8, f: 12, v: 11, '\\': 92, '"': 34, "'": 39, '?': 63 };
        const v = map[/** @type {keyof typeof map} */ (e)];
        bytes.push(v ?? e.charCodeAt(0));
      }
    } else {
      bytes.push(ch.charCodeAt(0));
      i++;
    }
  }
  return Uint8Array.from(bytes);
}

/**
 * `uint8_t NAME[...] = {...};` / `= "...";` をすべて集める。
 * @param {string} text - コメント除去済み
 * @returns {Map<string, Uint8Array>}
 */
function collectByteArrays(text) {
  /** @type {Map<string, Uint8Array>} */
  const out = new Map();
  // 配列名の後ろには PROGMEM / LGFXFT_PROGMEM / U8G2_FONT_SECTION("...") などの
  // 修飾マクロ（引数付き含む）が来ることがある
  const declRe =
    /(?:const|constexpr|static|PROGMEM|unsigned|\s)*(?:uint8_t|unsigned\s+char)\s+(\w+)\s*\[[^\]]*\]\s*(?:\w+(?:\([^)]*\))?\s*)*=\s*/g;
  let m;
  while ((m = declRe.exec(text)) !== null) {
    const name = m[1];
    const at = declRe.lastIndex;
    // 直後が '{' なら数値リスト、'"'（空白を挟むかもしれない）なら文字列リテラル
    const rest = text.slice(at, at + 8);
    if (rest.trimStart().startsWith('{')) {
      const open = text.indexOf('{', at);
      const close = text.indexOf('};', open);
      if (open < 0 || close < 0) continue;
      out.set(name, parseByteList(text.slice(open + 1, close)));
      declRe.lastIndex = close;
    } else if (rest.trimStart().startsWith('"')) {
      out.set(name, parseCStringLiterals(text, at));
    }
  }
  return out;
}

/**
 * `GFXglyph NAME[] = { {..}, ... };` をすべて集める。
 * @param {string} text
 * @returns {Map<string, GfxGlyphRec[]>}
 */
function collectGlyphArrays(text) {
  /** @type {Map<string, GfxGlyphRec[]>} */
  const out = new Map();
  const declRe = /GFXglyph\s+(\w+)\s*\[[^\]]*\]\s*(?:\w+\s*)*=\s*\{/g;
  let m;
  while ((m = declRe.exec(text)) !== null) {
    const close = text.indexOf('};', declRe.lastIndex);
    if (close < 0) continue;
    const body = text.slice(declRe.lastIndex, close);
    /** @type {GfxGlyphRec[]} */
    const glyphs = [];
    const tupleRe = /\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}/g;
    let tm;
    while ((tm = tupleRe.exec(body)) !== null) {
      glyphs.push({
        bitmapOffset: Number(tm[1]),
        width: Number(tm[2]),
        height: Number(tm[3]),
        xAdvance: Number(tm[4]),
        xOffset: Number(tm[5]),
        yOffset: Number(tm[6]),
      });
    }
    out.set(m[1], glyphs);
  }
  return out;
}

/**
 * `EncodeRange NAME[] = { {s,e,b}, ... };` をすべて集める。
 * @param {string} text
 * @returns {Map<string, {start: number, end: number, base: number}[]>}
 */
function collectRangeArrays(text) {
  /** @type {Map<string, {start: number, end: number, base: number}[]>} */
  const out = new Map();
  const declRe = /EncodeRange\s+(\w+)\s*\[[^\]]*\]\s*(?:\w+\s*)*=\s*\{/g;
  let m;
  while ((m = declRe.exec(text)) !== null) {
    const close = text.indexOf('};', declRe.lastIndex);
    if (close < 0) continue;
    const body = text.slice(declRe.lastIndex, close);
    const ranges = [];
    const tupleRe = /\{\s*(0[xX][0-9a-fA-F]+|\d+)\s*,\s*(0[xX][0-9a-fA-F]+|\d+)\s*,\s*(0[xX][0-9a-fA-F]+|\d+)\s*\}/g;
    let tm;
    while ((tm = tupleRe.exec(body)) !== null) {
      ranges.push({ start: Number(tm[1]), end: Number(tm[2]), base: Number(tm[3]) });
    }
    out.set(m[1], ranges);
  }
  return out;
}

/**
 * C/C++ ソーステキストからフォントをデコードする（1 ファイル複数フォント対応）。
 *
 * 対応:
 * - GFXfont 構造体（Adafruit GFX の .h、LovyanGFX 拡張の EncodeRange 付き含む）
 * - u8g2 のバイト配列（数値リスト・文字列リテラルのどちらも。bdfconv / fontgen /
 *   本ライブラリの出力）
 *
 * @param {string} source
 * @returns {{name: string, format: 'gfx' | 'u8g2', font: Font}[]}
 */
export function decodeCSource(source) {
  const text = stripComments(source);
  const arrays = collectByteArrays(text);
  const glyphArrays = collectGlyphArrays(text);
  const rangeArrays = collectRangeArrays(text);

  /** @type {{name: string, format: 'gfx' | 'u8g2', font: Font}[]} */
  const fonts = [];
  const used = new Set();

  // --- GFXfont 構造体 ---
  const structRe = /GFXfont\s+(\w+)\s*(?:\w+\s*)*=\s*\{([\s\S]*?)\};/g;
  let m;
  while ((m = structRe.exec(text)) !== null) {
    const name = m[1];
    const body = m[2];
    // 参照している配列名（bitmap → glyph → range の出現順）
    const refs = [...body.matchAll(/\b(\w+)\b/g)].map((r) => r[1]);
    const bitmapSym = refs.find((r) => arrays.has(r));
    const glyphSym = refs.find((r) => glyphArrays.has(r));
    const rangeSym = refs.find((r) => rangeArrays.has(r));
    if (!bitmapSym || !glyphSym) continue;
    const nums = body.match(/(?<![\w.])(?:0[xX][0-9a-fA-F]+|\d+)(?![\w.])/g)?.map(Number) ?? [];
    // 数値は first, last, yAdvance [, rangeNum] の順で現れる
    if (nums.length < 3) continue;
    const [first, last, yAdvance] = nums;
    used.add(bitmapSym);
    fonts.push({
      name,
      format: 'gfx',
      font: decodeGfx(
        packGfxContainer({
          first,
          last,
          yAdvance,
          ranges: rangeSym ? rangeArrays.get(rangeSym) ?? [] : [],
          glyphs: glyphArrays.get(glyphSym) ?? [],
          bitmap: arrays.get(bitmapSym) ?? new Uint8Array(0),
        }),
        { familyName: name },
      ),
    });
  }

  // U8g2font ラッパ宣言（lgfx::U8g2font NAME(NAME_data) 等）があれば、
  // データ配列名ではなくフォント名の方を採る
  const wrapperNames = new Map();
  const wrapRe = /\bU8g2font\s+(\w+)\s*\(\s*(\w+)\s*\)/g;
  while ((m = wrapRe.exec(text)) !== null) {
    wrapperNames.set(m[2], m[1]);
  }

  // --- 残りのバイト配列を u8g2 として試す ---
  for (const [name, bytes] of arrays) {
    if (used.has(name) || bytes.length < 30) continue;
    try {
      const fontName = wrapperNames.get(name) ?? name;
      const font = decodeU8g2(bytes, { familyName: fontName });
      if (font.glyphs.size > 0) fonts.push({ name: fontName, format: 'u8g2', font });
    } catch {
      // u8g2 ではない配列（画像など）は黙って読み飛ばす
    }
  }

  return fonts;
}
