// @ts-check
/**
 * C/C++ source output (spec §6.3, UC1). Generates headers ready for sketches.
 *
 * - u8g2: byte array plus an lgfx::U8g2font wrapper, following the
 *   LGFXScreenBuilder fontgen emitter; usable directly with setFont(&Name).
 * - gfx: Adafruit-style Bitmaps / Glyphs / GFXfont. Sparse character sets use
 *   LovyanGFX's EncodeRange extension and are therefore LovyanGFX-only.
 * - vlw / bff: embeds the binary unchanged as a uint8_t array for loading with
 *   LovyanGFX display.loadFont(array, font_type).
 *
 * Generated output always starts with attribution (spec §6.3 / §8.4). OFL and
 * Apache terms require notices to accompany derived font data.
 */
import { encodeU8g2, decodeU8g2 } from './u8g2.js';
import { encodeGfx, decodeGfx, unpackGfxContainer, packGfxContainer } from './gfxfont.js';
import { encodeVlw } from './vlw.js';
import { encodeBff } from './bff.js';
import { FormatError } from '../util/errors.js';

/** @typedef {import('../model/font.js').Font} Font */
/** @typedef {import('./gfxfont.js').GfxGlyphRec} GfxGlyphRec */

/** @param {number} b */
const HEX = (b) => '0x' + b.toString(16).padStart(2, '0');

/**
 * Converts user input to a C identifier, adding a prefix when it starts with a digit.
 * @param {string} name
 */
export function sanitizeIdent(name) {
  const s = String(name || '').replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(s) ? s : 'font_' + s;
}

/**
 * Summarizes code points as "U+0020-U+007E, U+00B0".
 * @param {number[]} cps
 * @param {number} [limit]
 */
export function summarizeRanges(cps, limit = 24) {
  if (!cps.length) return '(none)';
  /** @type {string[]} */
  const parts = [];
  const fmt = (/** @type {number} */ v) => `U+${v.toString(16).toUpperCase().padStart(4, '0')}`;
  let start = cps[0];
  let prev = cps[0];
  const push = () => parts.push(start === prev ? fmt(start) : `${fmt(start)}-${fmt(prev)}`);
  for (const c of cps.slice(1)) {
    if (c === prev + 1) {
      prev = c;
      continue;
    }
    push();
    start = prev = c;
  }
  push();
  if (parts.length <= limit) return parts.join(', ');
  return parts.slice(0, limit).join(', ') + `, … (+${parts.length - limit} more ranges)`;
}

/**
 * @typedef {object} Attribution
 * @property {string} [typeface] - source typeface name
 * @property {string} [author]
 * @property {string} [license]  - license name, e.g. 'SIL Open Font License 1.1'
 * @property {string} [licenseUrl]
 * @property {string} [origin]   - source location
 */

/**
 * Builds the attribution/provenance notice separately so the UI can preview it.
 * @param {Font} font
 * @param {{ident: string, format: string, bytes: number, attribution?: Attribution}} info
 */
export function licenseNotice(font, info) {
  const a = info.attribution ?? {};
  const cps = [...font.glyphs.keys()].sort((x, y) => x - y);
  const L = [];
  L.push(`${info.ident} — embedded bitmap font`);
  L.push('');
  L.push('Generated by LGFX Font Tool JS');
  L.push('https://github.com/tanakamasayuki/LGFXFontToolJs');
  L.push('');
  L.push(`Typeface : ${a.typeface || font.familyName || '(unknown)'}`);
  if (a.author) L.push(`Author   : ${a.author}`);
  if (a.license || font.meta.license) {
    L.push(`License  : ${a.license ?? font.meta.license}`);
    if (a.licenseUrl) L.push(`           ${a.licenseUrl}`);
  } else {
    L.push('License  : UNKNOWN — supplied as a local file.');
    L.push('           You are responsible for confirming that this typeface may be');
    L.push('           embedded and redistributed in compiled firmware.');
  }
  if (a.origin) L.push(`Obtained : ${a.origin}`);
  if (font.meta.copyright) L.push(`Copyright: ${font.meta.copyright}`);
  L.push('');
  L.push('This file contains glyphs rasterized from the typeface above and is a');
  L.push('derived work of it. Keep this notice with the file and with any binary');
  L.push('built from it.');
  L.push('');
  L.push(`Format   : ${info.format}`);
  L.push(`Line box : ${font.ascent + font.descent}px (ascent ${font.ascent}, descent ${font.descent})`);
  L.push(`Glyphs   : ${font.glyphs.size}`);
  L.push(`Data     : ${info.bytes} bytes`);
  L.push(`Coverage : ${summarizeRanges(cps)}`);
  return L.join('\n');
}

/** @param {Uint8Array} data @param {string} indent */
function hexTable(data, indent) {
  const PER_LINE = 16;
  let s = '';
  for (let i = 0; i < data.length; i += PER_LINE) {
    s +=
      indent +
      Array.from(data.slice(i, i + PER_LINE), HEX).join(', ') +
      (i + PER_LINE < data.length ? ',' : '') +
      '\n';
  }
  return s;
}

/** @param {string} notice */
const asComment = (notice) => '// ' + notice.split('\n').join('\n// ') + '\n';

const PROGMEM_GUARD = `#ifndef LGFXFT_PROGMEM
  #if defined(PROGMEM)
    #define LGFXFT_PROGMEM PROGMEM
  #else
    #define LGFXFT_PROGMEM
  #endif
#endif
`;

/** @typedef {'en'|'ja'|'zh-Hans'|'zh-Hant'} CSourceLanguage */

const HEADER_COMMENTS = {
  en: {
    u8g2Include: 'Include LovyanGFX (or M5GFX / M5Unified) before this header so lgfx::U8g2font is available.',
    gfxRange: 'EncodeRange is a LovyanGFX extension and works only with LovyanGFX / M5GFX.',
    gfxPlain: 'Adafruit GFX compatible; use gfxfont.h with Adafruit_GFX, or include directly with LovyanGFX.',
    runtimeInclude: 'Include LovyanGFX (or M5GFX / M5Unified) before this header.',
    usage: 'Usage',
    runtimeActive: 'On success, loadFont also selects this as the display\'s current font.',
  },
  ja: {
    u8g2Include: 'LovyanGFX（または同じ型を再輸出する M5GFX / M5Unified）を先に include して、lgfx::U8g2font が見える状態にしてください。',
    gfxRange: 'EncodeRange は LovyanGFX の拡張です。LovyanGFX / M5GFX 系でのみ使えます。',
    gfxPlain: 'Adafruit GFX 互換です。Adafruit_GFX では gfxfont.h、LovyanGFX ではそのまま使えます。',
    runtimeInclude: 'LovyanGFX（または M5GFX / M5Unified）を先に include してください。',
    usage: '使い方',
    runtimeActive: 'loadFont は成功すると、このフォントを表示先の現在フォントに設定します。',
  },
  'zh-Hans': {
    u8g2Include: '请先包含 LovyanGFX（或 M5GFX / M5Unified），以便使用 lgfx::U8g2font。',
    gfxRange: 'EncodeRange 是 LovyanGFX 扩展，仅适用于 LovyanGFX / M5GFX。',
    gfxPlain: '兼容 Adafruit GFX；Adafruit_GFX 请使用 gfxfont.h，LovyanGFX 可直接使用。',
    runtimeInclude: '请先包含 LovyanGFX（或 M5GFX / M5Unified）。',
    usage: '用法',
    runtimeActive: 'loadFont 成功后还会将此字体设为显示设备的当前字体。',
  },
  'zh-Hant': {
    u8g2Include: '請先包含 LovyanGFX（或 M5GFX / M5Unified），以便使用 lgfx::U8g2font。',
    gfxRange: 'EncodeRange 是 LovyanGFX 擴充，僅適用於 LovyanGFX / M5GFX。',
    gfxPlain: '相容 Adafruit GFX；Adafruit_GFX 請使用 gfxfont.h，LovyanGFX 可直接使用。',
    runtimeInclude: '請先包含 LovyanGFX（或 M5GFX / M5Unified）。',
    usage: '用法',
    runtimeActive: 'loadFont 成功後也會將此字型設為顯示裝置的目前字型。',
  },
};

/** @param {CSourceLanguage | undefined} language */
const headerComments = (language) => HEADER_COMMENTS[language ?? 'en'] ?? HEADER_COMMENTS.en;

/**
 * Emits a u8g2 header.
 * @param {Font} font
 * @param {string} ident
 * @param {Attribution | undefined} attribution
 * @param {{dropInvalid?: boolean}} encodeOpts
 * @param {CSourceLanguage | undefined} language
 */
function emitU8g2Header(font, ident, attribution, encodeOpts, language) {
  const data = encodeU8g2(font, encodeOpts);
  const comments = headerComments(language);
  const guard = `LGFXFT_FONT_${ident.toUpperCase()}_H`;
  let s = asComment(
    licenseNotice(font, { ident, format: 'u8g2 (1bpp) — lgfx::U8g2font', bytes: data.length, attribution }),
  );
  s += '\n';
  s += `#ifndef ${guard}\n#define ${guard}\n\n`;
  s += '#include <stdint.h>\n\n';
  s += `// ${comments.u8g2Include}\n`;
  s += '#if !defined(LGFX_USE_V1) && !defined(__LOVYANGFX_HPP__) && !defined(_M5GFX_H_)\n';
  s += '  #include <LovyanGFX.hpp>\n';
  s += '#endif\n\n';
  s += PROGMEM_GUARD + '\n';
  s += `static const uint8_t ${ident}_data[${data.length}] LGFXFT_PROGMEM = {\n`;
  s += hexTable(data, '  ');
  s += '};\n\n';
  s += `// ${comments.usage}:  display.setFont(&${ident});\n`;
  s += `static const lgfx::U8g2font ${ident}(${ident}_data);\n\n`;
  s += `#endif // ${guard}\n`;
  return s;
}

/**
 * Emits a GFXfont header. A single range is plain Adafruit GFX compatible;
 * sparse ranges use LovyanGFX's EncodeRange extension.
 * @param {Font} font
 * @param {string} ident
 * @param {Attribution | undefined} attribution
 * @param {{dropInvalid?: boolean}} encodeOpts
 * @param {CSourceLanguage | undefined} language
 */
function emitGfxHeader(font, ident, attribution, encodeOpts, language) {
  const gfx = unpackGfxContainer(encodeGfx(font, encodeOpts));
  const comments = headerComments(language);
  const ranged = gfx.ranges.length > 0;
  const bytes = gfx.bitmap.length + gfx.glyphs.length * 7 + gfx.ranges.length * 6 + 5;
  const guard = `LGFXFT_FONT_${ident.toUpperCase()}_H`;

  let s = asComment(
    licenseNotice(font, {
      ident,
      format: ranged
        ? 'GFXfont + EncodeRange (LovyanGFX extension; not plain Adafruit GFX)'
        : 'GFXfont (Adafruit GFX compatible)',
      bytes,
      attribution,
    }),
  );
  s += '\n';
  s += `#ifndef ${guard}\n#define ${guard}\n\n`;
  s += '#include <stdint.h>\n\n';
  if (ranged) {
    s += `// ${comments.gfxRange}\n`;
    s += '#if !defined(LGFX_USE_V1) && !defined(__LOVYANGFX_HPP__) && !defined(_M5GFX_H_)\n';
    s += '  #include <LovyanGFX.hpp>\n';
    s += '#endif\n\n';
  } else {
    s += `// ${comments.gfxPlain}\n\n`;
  }
  s += PROGMEM_GUARD + '\n';

  s += `static const uint8_t ${ident}Bitmaps[] LGFXFT_PROGMEM = {\n`;
  s += hexTable(gfx.bitmap, '  ');
  s += '};\n\n';

  const typePrefix = ranged ? 'lgfx::v1::' : '';
  s += `static const ${typePrefix}GFXglyph ${ident}Glyphs[] LGFXFT_PROGMEM = {\n`;
  gfx.glyphs.forEach((g, i) => {
    s += `  { ${g.bitmapOffset}, ${g.width}, ${g.height}, ${g.xAdvance}, ${g.xOffset}, ${g.yOffset} }${
      i + 1 < gfx.glyphs.length ? ',' : ''
    }\n`;
  });
  s += '};\n\n';

  if (ranged) {
    s += `static const lgfx::v1::EncodeRange ${ident}Ranges[] LGFXFT_PROGMEM = {\n`;
    gfx.ranges.forEach((r, i) => {
      s += `  { 0x${r.start.toString(16)}, 0x${r.end.toString(16)}, 0x${r.base.toString(16)} }${
        i + 1 < gfx.ranges.length ? ',' : ''
      }\n`;
    });
    s += '};\n\n';
    s += `// ${comments.usage}:  display.setFont(&${ident});\n`;
    s += `static const lgfx::v1::GFXfont ${ident} = {\n`;
    s += `  (uint8_t*)${ident}Bitmaps,\n`;
    s += `  (lgfx::v1::GFXglyph*)${ident}Glyphs,\n`;
    s += `  0x${gfx.first.toString(16)}, 0x${gfx.last.toString(16)}, ${gfx.yAdvance},\n`;
    s += `  ${gfx.ranges.length}, (lgfx::v1::EncodeRange*)${ident}Ranges };\n\n`;
  } else {
    s += `// ${comments.usage}:  display.setFont(&${ident});\n`;
    s += `static const GFXfont ${ident} LGFXFT_PROGMEM = {\n`;
    s += `  (uint8_t*)${ident}Bitmaps,\n`;
    s += `  (GFXglyph*)${ident}Glyphs,\n`;
    s += `  0x${gfx.first.toString(16)}, 0x${gfx.last.toString(16)}, ${gfx.yAdvance} };\n\n`;
  }
  s += `#endif // ${guard}\n`;
  return s;
}

/**
 * Embeds a VLW / BFF binary unchanged as a C array. LovyanGFX
 * loadFont(const uint8_t*, font_type) creates the PointerWrapper internally.
 * @param {Font} font
 * @param {string} ident
 * @param {Attribution | undefined} attribution
 * @param {'vlw'|'bff'} format
 * @param {{dropInvalid?: boolean, bpp?: 1|2|4}} encodeOpts
 * @param {CSourceLanguage | undefined} language
 */
function emitRuntimeHeader(font, ident, attribution, format, encodeOpts, language) {
  const data =
    format === 'vlw'
      ? encodeVlw(font, { dropInvalid: encodeOpts.dropInvalid })
      : encodeBff(font, encodeOpts);
  const guard = `LGFXFT_FONT_${ident.toUpperCase()}_H`;
  const comments = headerComments(language);
  const isBff = format === 'bff';
  const formatLabel = isBff
    ? 'BFF (1–4bpp) — LovyanGFX runtime font'
    : 'VLW (8bpp) — LovyanGFX runtime font';
  const loadArgs = isBff
    ? `${ident}_data, lgfx::IFont::font_type_t::ft_lvgl`
    : `${ident}_data`;

  let s = asComment(licenseNotice(font, { ident, format: formatLabel, bytes: data.length, attribution }));
  s += '\n';
  s += `#ifndef ${guard}\n#define ${guard}\n\n`;
  s += '#include <stdint.h>\n\n';
  s += `// ${comments.runtimeInclude}\n`;
  s += '#if !defined(LGFX_USE_V1) && !defined(__LOVYANGFX_HPP__) && !defined(_M5GFX_H_)\n';
  s += '  #include <LovyanGFX.hpp>\n';
  s += '#endif\n\n';
  s += PROGMEM_GUARD + '\n';
  s += `static const uint8_t ${ident}_data[${data.length}] LGFXFT_PROGMEM = {\n`;
  s += hexTable(data, '  ');
  s += '};\n\n';
  s += `// ${comments.usage}:  display.loadFont(${loadArgs});\n`;
  s += `// ${comments.runtimeActive}\n\n`;
  s += `#endif // ${guard}\n`;
  return s;
}

/**
 * Emits C/C++ source ready for inclusion in a sketch (spec §6.3).
 * @param {Font} font
 * @param {object} opts
 * @param {'u8g2' | 'gfx' | 'vlw' | 'bff'} opts.format
 * @param {string} opts.symbolName - C identifier for the font object/data
 * @param {Attribution} [opts.attribution]
 * @param {boolean} [opts.dropInvalid] - drop invalid glyphs instead of failing (default false)
 * @param {1|2|4} [opts.bpp] - BFF output depth
 * @param {CSourceLanguage} [opts.language] - generated operational-comment language (default `en`)
 * @returns {string}
 */
export function encodeCSource(font, opts) {
  const ident = sanitizeIdent(opts.symbolName);
  const encodeOpts = { dropInvalid: opts.dropInvalid, bpp: opts.bpp };
  switch (opts.format) {
    case 'u8g2':
      return emitU8g2Header(font, ident, opts.attribution, encodeOpts, opts.language);
    case 'gfx':
      return emitGfxHeader(font, ident, opts.attribution, encodeOpts, opts.language);
    case 'vlw':
    case 'bff':
      return emitRuntimeHeader(font, ident, opts.attribution, opts.format, encodeOpts, opts.language);
    default:
      throw new FormatError('UNKNOWN_FORMAT', `no C source emitter for ${opts.format}`, {
        format: opts.format,
      });
  }
}

//----------------------------------------------------------------------------
// C/C++ source input (spec §6.3, UC5). This accepts real-world headers and
// source files distributed on GitHub or in Arduino libraries; it deliberately
// does not implement a complete C preprocessor.

/** @param {string} text */
function stripComments(text) {
  return text.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/\/\/[^\n]*/g, ' ');
}

/**
 * Parses a numeric list inside `{ ... }` into bytes.
 * @param {string} body
 */
function parseByteList(body) {
  const bytes = [];
  const re = /0[xX][0-9a-fA-F]+|\d+/g;
  let m;
  while ((m = re.exec(body)) !== null) bytes.push(Number(m[0]) & 0xff);
  return Uint8Array.from(bytes);
}

/**
 * Parses concatenated C string literals, including octal and hex escapes,
 * into bytes. This is the form emitted by u8g2 bdfconv.
 * @param {string} text
 * @param {number} start - immediately after `=`
 * @returns {Uint8Array}
 */
function parseCStringLiterals(text, start) {
  const bytes = [];
  let i = start;
  const n = text.length;
  let inString = false;
  while (i < n) {
    const ch = text[i];
    if (!inString) {
      if (ch === '"') {
        inString = true;
        i++;
      } else if (ch === ';') {
        break;
      } else {
        i++;
      }
      continue;
    }
    if (ch === '"') {
      inString = false;
      i++;
      continue;
    }
    if (ch === '\\') {
      i++;
      const e = text[i];
      if (e >= '0' && e <= '7') {
        let oct = '';
        while (oct.length < 3 && text[i] >= '0' && text[i] <= '7') oct += text[i++];
        bytes.push(parseInt(oct, 8) & 0xff);
      } else if (e === 'x') {
        i++;
        let hex = '';
        while (/[0-9a-fA-F]/.test(text[i])) hex += text[i++];
        bytes.push(parseInt(hex, 16) & 0xff);
      } else {
        i++;
        const map = { n: 10, t: 9, r: 13, a: 7, b: 8, f: 12, v: 11, '\\': 92, '"': 34, "'": 39, '?': 63 };
        const v = map[/** @type {keyof typeof map} */ (e)];
        bytes.push(v ?? e.charCodeAt(0));
      }
    } else {
      bytes.push(ch.charCodeAt(0));
      i++;
    }
  }
  return Uint8Array.from(bytes);
}

/**
 * Collects all `uint8_t NAME[...] = {...};` / `= "...";` declarations.
 * @param {string} text - comment-stripped source
 * @returns {Map<string, Uint8Array>}
 */
function collectByteArrays(text) {
  /** @type {Map<string, Uint8Array>} */
  const out = new Map();
  // Qualifier macros such as PROGMEM, LGFXFT_PROGMEM, or
  // U8G2_FONT_SECTION("...") may follow the array name.
  const declRe =
    /(?:const|constexpr|static|PROGMEM|unsigned|\s)*(?:uint8_t|unsigned\s+char)\s+(\w+)\s*\[[^\]]*\]\s*(?:\w+(?:\([^)]*\))?\s*)*=\s*/g;
  let m;
  while ((m = declRe.exec(text)) !== null) {
    const name = m[1];
    const at = declRe.lastIndex;
    // A following `{` starts a numeric list; `"` (possibly after whitespace)
    // starts a string literal.
    const rest = text.slice(at, at + 8);
    if (rest.trimStart().startsWith('{')) {
      const open = text.indexOf('{', at);
      const close = text.indexOf('};', open);
      if (open < 0 || close < 0) continue;
      out.set(name, parseByteList(text.slice(open + 1, close)));
      declRe.lastIndex = close;
    } else if (rest.trimStart().startsWith('"')) {
      out.set(name, parseCStringLiterals(text, at));
    }
  }
  return out;
}

/**
 * Collects all `GFXglyph NAME[] = { {..}, ... };` declarations.
 * @param {string} text
 * @returns {Map<string, GfxGlyphRec[]>}
 */
function collectGlyphArrays(text) {
  /** @type {Map<string, GfxGlyphRec[]>} */
  const out = new Map();
  const declRe = /GFXglyph\s+(\w+)\s*\[[^\]]*\]\s*(?:\w+\s*)*=\s*\{/g;
  let m;
  while ((m = declRe.exec(text)) !== null) {
    const close = text.indexOf('};', declRe.lastIndex);
    if (close < 0) continue;
    const body = text.slice(declRe.lastIndex, close);
    /** @type {GfxGlyphRec[]} */
    const glyphs = [];
    const tupleRe = /\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}/g;
    let tm;
    while ((tm = tupleRe.exec(body)) !== null) {
      glyphs.push({
        bitmapOffset: Number(tm[1]),
        width: Number(tm[2]),
        height: Number(tm[3]),
        xAdvance: Number(tm[4]),
        xOffset: Number(tm[5]),
        yOffset: Number(tm[6]),
      });
    }
    out.set(m[1], glyphs);
  }
  return out;
}

/**
 * Collects all `EncodeRange NAME[] = { {s,e,b}, ... };` declarations.
 * @param {string} text
 * @returns {Map<string, {start: number, end: number, base: number}[]>}
 */
function collectRangeArrays(text) {
  /** @type {Map<string, {start: number, end: number, base: number}[]>} */
  const out = new Map();
  const declRe = /EncodeRange\s+(\w+)\s*\[[^\]]*\]\s*(?:\w+\s*)*=\s*\{/g;
  let m;
  while ((m = declRe.exec(text)) !== null) {
    const close = text.indexOf('};', declRe.lastIndex);
    if (close < 0) continue;
    const body = text.slice(declRe.lastIndex, close);
    const ranges = [];
    const tupleRe = /\{\s*(0[xX][0-9a-fA-F]+|\d+)\s*,\s*(0[xX][0-9a-fA-F]+|\d+)\s*,\s*(0[xX][0-9a-fA-F]+|\d+)\s*\}/g;
    let tm;
    while ((tm = tupleRe.exec(body)) !== null) {
      ranges.push({ start: Number(tm[1]), end: Number(tm[2]), base: Number(tm[3]) });
    }
    out.set(m[1], ranges);
  }
  return out;
}

/**
 * Decodes fonts from C/C++ source text; supports multiple fonts per file.
 *
 * Supported forms:
 * - GFXfont structs, including LovyanGFX EncodeRange extensions
 * - u8g2 byte arrays as numeric lists or string literals from bdfconv,
 *   fontgen, or this library
 *
 * @param {string} source
 * @returns {{name: string, format: 'gfx' | 'u8g2', font: Font}[]}
 */
export function decodeCSource(source) {
  const text = stripComments(source);
  const arrays = collectByteArrays(text);
  const glyphArrays = collectGlyphArrays(text);
  const rangeArrays = collectRangeArrays(text);

  /** @type {{name: string, format: 'gfx' | 'u8g2', font: Font}[]} */
  const fonts = [];
  const used = new Set();

  // --- GFXfont structs ---
  const structRe = /GFXfont\s+(\w+)\s*(?:\w+\s*)*=\s*\{([\s\S]*?)\};/g;
  let m;
  while ((m = structRe.exec(text)) !== null) {
    const name = m[1];
    const body = m[2];
    // Referenced array names in bitmap, glyph, range order.
    const refs = [...body.matchAll(/\b(\w+)\b/g)].map((r) => r[1]);
    const bitmapSym = refs.find((r) => arrays.has(r));
    const glyphSym = refs.find((r) => glyphArrays.has(r));
    const rangeSym = refs.find((r) => rangeArrays.has(r));
    if (!bitmapSym || !glyphSym) continue;
    const nums = body.match(/(?<![\w.])(?:0[xX][0-9a-fA-F]+|\d+)(?![\w.])/g)?.map(Number) ?? [];
    // Numeric fields appear as first, last, yAdvance [, rangeNum].
    if (nums.length < 3) continue;
    const [first, last, yAdvance] = nums;
    used.add(bitmapSym);
    fonts.push({
      name,
      format: 'gfx',
      font: decodeGfx(
        packGfxContainer({
          first,
          last,
          yAdvance,
          ranges: rangeSym ? rangeArrays.get(rangeSym) ?? [] : [],
          glyphs: glyphArrays.get(glyphSym) ?? [],
          bitmap: arrays.get(bitmapSym) ?? new Uint8Array(0),
        }),
        { familyName: name },
      ),
    });
  }

  // Prefer the font name from an U8g2font wrapper declaration such as
  // lgfx::U8g2font NAME(NAME_data), rather than the backing array name.
  const wrapperNames = new Map();
  const wrapRe = /\bU8g2font\s+(\w+)\s*\(\s*(\w+)\s*\)/g;
  while ((m = wrapRe.exec(text)) !== null) {
    wrapperNames.set(m[2], m[1]);
  }

  // --- Try remaining byte arrays as u8g2 ---
  for (const [name, bytes] of arrays) {
    if (used.has(name) || bytes.length < 30) continue;
    try {
      const fontName = wrapperNames.get(name) ?? name;
      const font = decodeU8g2(bytes, { familyName: fontName });
      if (font.glyphs.size > 0) fonts.push({ name: fontName, format: 'u8g2', font });
    } catch {
      // Silently skip non-u8g2 arrays such as images.
    }
  }

  return fonts;
}
